### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by Solemnly** [turicas/crau#13] opened 2019-11-06 11:46 UTC
Fresh installed & updated Ubuntu 18.04.03

>  crau archive bild.warc.gz https://bild.de
Traceback (most recent call last):
  File "/usr/local/bin/crau", line 11, in <module>
    load_entry_point('crau==0.1.0', 'console_scripts', 'crau')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/crau/__init__.py", line 1, in <module>
    from .spider import CrauSpider
  File "/usr/local/lib/python2.7/dist-packages/crau/spider.py", line 101
    f"{request.method} {path} HTTP/1.1", headers_list, is_http_request=True
                                      ^
SyntaxError: invalid syntax

**Comment by turicas** [comment] 2019-11-06 15:47
Hi, @Solemnly. You're using Python 2.7 and `crau` was developed and tested under Python 3.7.5. The [Python f-strings syntax was introduced in version 3.6](https://docs.python.org/3/whatsnew/3.6.html) and this version may work (instead of 3.7). Please install an earlier Python version on your system ([Python 2 is gonna die](https://pythonclock.org/)) and try again.

Since it's not a bug, I'm closing the issue.

**Closed by turicas** 2019-11-06 15:47 UTC
